[tool.poetry]
name = "voivid"
version = "0.1.0"
description = "Telegram bot with FFmpeg"
authors = ["limbogeom@gmail.com"]

[tool.poetry.dependencies]
python = "^3.11"
pyTelegramBotAPI = "^4.15.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
